# Generated by Django 2.2 on 2019-05-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.IntegerField(default=0)),
                ('destination', models.URLField()),
                ('code', models.TextField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
