# Generated by Django 2.2 on 2019-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten_url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='code',
            field=models.TextField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
